from enum import Enum

class InstagramPostingScreenNames(str, Enum):
    FINISH_ACCOUNT_SETUP_MODAL = "FINISH_ACCOUNT_SETUP_MODAL"
    HOME = "HOME"
    ON_MAKE_POST = "ON_MAKE_POST"
    ON_MAKE_STORY = "ON_MAKE_STORY"
    NEW_POST = "NEW_POST"
    SIMPLIFIED_NAVIGATION_MODAL = "SIMPLIFIED_NAVIGATION_MODAL"